name: Vote Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 mins
  workflow_dispatch:

jobs:
  vote-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin

      - name: Run Vote Script
        run: python bot.py
